# Generated by Django 3.2 on 2021-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('num_of_seats', models.IntegerField()),
                ('table_shape', models.IntegerField()),
                ('coordinate_x', models.IntegerField()),
                ('coordinate_y', models.IntegerField()),
                ('size_width', models.IntegerField()),
                ('size_length', models.IntegerField()),
                ('reserved_status', models.BooleanField()),
            ],
        ),
    ]
